name = "feedback"
main = ".output/server/index.mjs"
workers_dev = true
account_id = "fe5d9bd14160b07939282e45f63eb5ad"
compatibility_date = "2022-09-10"

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 30 }
